import Head from "next/head";
import Nav from "../src/commons/Nav/Nav";
import HomePage from "./home/Home";

export default function Home() {
  return (
    <>
      <Head>
        <title>METAFOR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </>
  );
}
